#!/bin/bash
REPORT_FILE="/tmp/hardware_inventory_$(date +%Y%m%d_%H%M%S).txt"
echo "Generating comprehensive hardware inventory report..."
echo "Report will be saved to: $REPORT_FILE"

cat > "$REPORT_FILE" << 'REPORT_EOF'
================================================================================
 HARDWARE INVENTORY REPORT
================================================================================
REPORT_EOF

echo "Generated on: $(date)" >> "$REPORT_FILE"
echo "System: $(hostname)" >> "$REPORT_FILE"
echo "Generated by: $(whoami)" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# System Information
cat >> "$REPORT_FILE" << 'SYS_EOF'
================================================================================
SYSTEM INFORMATION
================================================================================
SYS_EOF
sudo dmidecode --type 1 >> "$REPORT_FILE"

# BIOS Information
cat >> "$REPORT_FILE" << 'BIOS_EOF'
================================================================================
BIOS INFORMATION
================================================================================
BIOS_EOF
sudo dmidecode --type 0 >> "$REPORT_FILE"

# Motherboard Information
cat >> "$REPORT_FILE" << 'MB_EOF'
================================================================================
MOTHERBOARD INFORMATION
================================================================================
MB_EOF
sudo dmidecode --type 2 >> "$REPORT_FILE"

# Processor Information
cat >> "$REPORT_FILE" << 'CPU_EOF'
================================================================================
PROCESSOR INFORMATION
================================================================================
CPU_EOF
sudo dmidecode --type 4 >> "$REPORT_FILE"

# Memory Information
cat >> "$REPORT_FILE" << 'MEM_EOF'
================================================================================
MEMORY INFORMATION
================================================================================
MEM_EOF
sudo dmidecode --type 16,17 >> "$REPORT_FILE"

# System Slots
cat >> "$REPORT_FILE" << 'SLOTS_EOF'
================================================================================
SYSTEM SLOTS AND EXPANSION
================================================================================
SLOTS_EOF
sudo dmidecode --type 9 >> "$REPORT_FILE"

echo "Hardware inventory report generated successfully!"
echo "Report location: $REPORT_FILE"
echo ""
echo "To view the report:"
echo "less $REPORT_FILE"
